---
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Ensure environment file exists
    file:
      path: "{{ environment_file }}"
      owner: "{{ environment_file_owner }}"
      group: "{{ environment_file_group }}"
      state: touch
    register: environment_file_result
    changed_when: environment_file_result.diff.before.state != "file"

  - name: Configuring environment
    lineinfile:
      dest: "{{ environment_file }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^LANGUAGE=', line: 'LANGUAGE="en_US:en"' }
      - { regexp: '^LC_ALL=', line: 'LC_ALL="en_US.utf8"' }
      - { regexp: '^LC_CTYPE=', line: 'LC_CTYPE="en_US.utf8"' }
      - { regexp: '^LANG=', line: 'LANG="en_US.utf8"' }

  - name: Enable EPEL
    yum: name=epel-release

  - name: Install Spacewalk repository
    yum: name=https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.9/epel-{{ansible_distribution_major_version}}-x86_64/00830557-spacewalk-repo/spacewalk-repo-2.9-4.el{{ansible_distribution_major_version}}.noarch.rpm
    
  - name: Install Spacewalk-setup-postgresql
    yum: name=spacewalk-setup-postgresql state=present

  - name: Ensure hostname in /etc/hosts
    lineinfile: dest=/etc/hosts regexp=^{{ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])}} line="{{ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])}} spacewalk-test"

# Bug in Ansible <2.8, see Ansible Github issue 47210, enable if using Ansible >=2.8
#  - name: Install spacewalk-postgresql
#    yum: name=spacewalk-postgresql state=present

# Can be disabled if using Ansible >=2.8
  - name: Install spacewalk-postgresql (using work around for Ansible versions lower than 2.8)
    command: yum -y install spacewalk-postgresql
    async: 3600
    poll: 2
    register: yum_sleeper
    args:
      warn: false

  - name: YUM - check on spacewalk-postgresql installation
    async_status:
      jid: "{{ yum_sleeper.ansible_job_id }}"
    register: job_result
    until: job_result.finished
# End of codeblock that can be disabled when using Ansible >=2.8

  - name: initialize DB - bug 1524221
    command: postgresql-setup initdb
    args:
      creates: "/var/lib/pgsql/data/pg_ident.conf"

  - name: Copy answers file for spacewalk setip
    template: src=answers.j2 dest=/var/tmp/answers owner=root group=root mode=0600

  - name: Install spacewalk
    command: spacewalk-setup --answer-file=/var/tmp/answers
             creates=/var/satellite
  #- template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=0600
  #  notify: restart_iptables

